name: Publish Release
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create a Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh issue comment 1 -b "@jsdelivrbot purge https://cdn.jsdelivr.net/gh/dhuey/ferosys/src/index.js"
        # gh release delete nightly -y
        # gh release create nightly -t "Nightly"

