name: Publish Release
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create a Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_HOST: dhuey/ferosys/
      run: gh release delete nightly -y
      run: gh release create nightly -t "Nightly"

